# Generated by Django 3.2.5 on 2021-07-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('decision', models.IntegerField(choices=[('1', 'Approved'), ('0', 'Reject')], default=0, max_length=1)),
                ('remark', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.purpose')),
            ],
        ),
        migrations.CreateModel(
            name='Request_QTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('size_wise_qty', models.IntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestsample.request')),
            ],
        ),
    ]
