# Generated by Django 3.2.5 on 2021-07-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='decision',
            field=models.IntegerField(choices=[('1', 'Approved'), ('0', 'Reject')], default=0),
        ),
    ]
